kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk1-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hdd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk1-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hdd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-azuredisk1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azuredisk1
    spec:
      containers:
      - name: deployment-azuredisk1
        image: nginx
        command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azuredisk/outdisk; sleep 1; done		
        volumeMounts:
        - name: azuredisk1
          mountPath: "/mnt/azuredisk1"
        - name: azuredisk2
          mountPath: "/mnt/azuredisk2"
      volumes:
      - name: azuredisk1
        persistentVolumeClaim:
          claimName: pvc-azuredisk1-1
      - name: azuredisk2
        persistentVolumeClaim:
          claimName: pvc-azuredisk1-2
