---
apiVersion: v1
kind: Pod
metadata:
  name: aspnet-csi-hostpath
spec:
  containers:
  - image: microsoft/aspnet
    name: aspnet-csi-hostpath
    volumeMounts:
    - name: csi-hostpath
      mountPath: 'D:'
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
   - name: csi-hostpath
     persistentVolumeClaim:
       claimName: pvc-csi-hostpath
       readOnly: false
