---
kind: Pod
apiVersion: v1
metadata:
  name: aspnet-azurefile
spec:
  containers:
  - image: mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
    name: aspnet-azurefile
    volumeMounts:
    - name: azurefile01
      mountPath: '/mnt/azure'
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
  - name: azurefile01
    persistentVolumeClaim:
      claimName: pvc-azurefile
