kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnet
  name: deployment-azurefile
spec:
  replicas: 6
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
      name: deployment-azurefile
    spec:
      containers:
      - name: deployment-azurefile
        image: mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
        volumeMounts:
        - name: azurefile01
          mountPath: '/mnt/azure1'
      volumes:
      - name: azurefile01
        persistentVolumeClaim:
          claimName: pvc-azurefile
