kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
---
kind: Job
apiVersion: batch/v1
metadata:
  name: pi
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pi
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        volumeMounts:
        - name: azurefile
          mountPath: "/mnt/azurefile"
      volumes:
      - name: azurefile
        persistentVolumeClaim:
          claimName: pvc-azurefile
