---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aspnet-azuredisk
  name: aspnet-azuredisk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnet-azuredisk
      name: aspnet-azuredisk
    spec:
      containers:
      - name: aspnet-azuredisk
        image: mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
        volumeMounts:
        - name: disk01
          mountPath: 'D:'
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: disk01
        persistentVolumeClaim:
          claimName: pvc-azuredisk
