---
kind: Pod
apiVersion: v1
metadata:
  name: aspnet-azuredisk
spec:
  containers:
  - image: mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
    name: aspnet-azuredisk
    volumeMounts:
    - name: disk01
      mountPath: 'D:'
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
  - name: disk01
    persistentVolumeClaim:
      claimName: pvc-azuredisk

