apiVersion: v1
kind: Pod
metadata:
  name: aspnet-downwardapi
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
  annotations:
    build: two
    builder: john-doe  
spec:
  containers:
    - name: aspnet-downwardapi
      image: microsoft/aspnet:4.7.2-windowsservercore-1803
      volumeMounts:
        - name: podinfo
          mountPath: /mnt/azure
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
